image:
  - Visual Studio 2017
  - Visual Studio 2015

version: build-{build}

environment:
  CRYPTOPP_VERSION: 6_0_0
  CRYPTOPP_SHA512SUM: 4085c9b1aaefab3064b43126eec19c0f0240e641b145ed4d6ef4f2f446e7119f2f3904ce34171fbe3a30acbe69cbf2171f125756df45d6bd75184d50dc4f077c

  matrix:
    - PLATFORM: msvc2017_64
    - PLATFORM: msvc2017
    - PLATFORM: msvc2015_64
    - PLATFORM: msvc2015

matrix:
  exclude:
    - PLATFORM: msvc2017_64
      image: Visual Studio 2015
    - PLATFORM: msvc2017
      image: Visual Studio 2015
    - PLATFORM: msvc2015_64
      image: Visual Studio 2017
    - PLATFORM: msvc2015
      image: Visual Studio 2017

build_script:
  - .\cryptopp\appveyor.bat

artifacts:
  - path: cryptopp\cryptopp_%CRYPTOPP_VERSION%_%PLATFORM%.zip

deploy:
  provider: GitHub
  auth_token:
    secure: Cp5GRQku2ZWnKPE12NB5q11ZO0Fr5mlzdUTjnLpYJr/dki4LPVqm231edFggogy8
  artifact: /.*\.zip/
  force_update: false
  on:
    appveyor_repo_tag: true
