image:
  - Visual Studio 2017
  - Visual Studio 2015

version: build-{build}

environment:
  CRYPTOPP_VERSION: 7_0_0
  CRYPTOPP_SHA512SUM: 6a7a65783d9821a86066421c13d44737a0b99324fa923d400431232263c75f07dfeef38ade1b779ca50ba3aa9c6d54d20c262d91d30bbc16c696f103e37a790b

  matrix:
    - PLATFORM: msvc2017_64
    - PLATFORM: msvc2017
    - PLATFORM: mingw73_64
    - PLATFORM: msvc2015_64

matrix:
  exclude:
    - PLATFORM: msvc2017_64
      image: Visual Studio 2015
    - PLATFORM: msvc2017
      image: Visual Studio 2015
    - PLATFORM: mingw73_64
      image: Visual Studio 2015
    - PLATFORM: msvc2015_64
      image: Visual Studio 2017

build_script:
  - .\cryptopp\appveyor.bat

artifacts:
  - path: cryptopp\cryptopp_%CRYPTOPP_VERSION%_%PLATFORM%.zip

deploy:
  provider: GitHub
  auth_token:
    secure: Cp5GRQku2ZWnKPE12NB5q11ZO0Fr5mlzdUTjnLpYJr/dki4LPVqm231edFggogy8
  artifact: /.*\.zip/
  force_update: false
  on:
    appveyor_repo_tag: true
